trigger:
- main

pool:
  name: LocalPool2

jobs:
- job: BackendCI
  displayName: 'Build and Test Backend'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
  
  - script: |
      pip install -r requirements.txt
    workingDirectory: 'backend'
    displayName: 'Install Python dependencies'
  
  - script: |
      pip install pytest pytest-azurepipelines
      pytest --junitxml=test-results.xml
    workingDirectory: 'backend'
    displayName: 'Run backend tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/backend'
      testRunTitle: 'Backend Python Tests'
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'

- job: FrontendCI
  displayName: 'Build Frontend'
  steps:

  
  - script: |
      npm install
    workingDirectory: 'frontend'
    displayName: 'Install Node dependencies'
  
  - script: |
      npm run build
    workingDirectory: 'frontend'
    displayName: 'Build frontend assets'