# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
  
  - script: |
      pip install -r requirements.txt
    workingDirectory: 'backend'
    displayName: 'Install Python dependencies'
  
  - script: |
      pip install pytest pytest-azurepipelines
      pytest --junitxml=test-results.xml
    workingDirectory: 'backend'
    displayName: 'Run backend tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/backend'
      testRunTitle: 'Backend Python Tests'
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'